on:
  push:
    branches:
      - master
      - actions
  workflow_dispatch:

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Install build deps
        run: sudo apt-get install debhelper dput libqt5websockets5-dev qtbase5-dev
      - name: Build source package
        run: dpkg-buildpackage -S -kmichael_zanetti@gmx.net
      - name: Upload to repo
        run: dput ppa:mzanetti/testing ../nymea-mqtt*_source.changes
